name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
        - os: ubuntu-latest
        - os: windows-latest
        - os: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: gcc -fPIC -lm -shared src/stats.c -o dist/sqlite3-stats.so

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: gcc -fPIC -lm -shared src/stats.c -o dist/sqlite3-stats.dll

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: gcc -fno-common -dynamiclib src/stats.c -o dist/sqlite3-stats.dylib
