name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cmake --build .
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cpp_app
          path: |
            **/*.o
          retention-days: 5
