name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
        - os: ubuntu-latest
        - os: windows-latest
        - os: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: g++ hello.cpp -o hello_lin.o

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cl /EHsc hello.cpp
          -name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            name: cpp_app
            path: hello.exe
            retention-days: 5

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: g++ hello.cpp -o hello_mac.o
